### ISSUE TITLE
Adding Sleep Mode

### ISSUE THREAD

**Issue by JasonPittenger** [m5stack/M5UnitKMeter_Firmware#2]
Is there a way to add a command to put the Kmeter to sleep?
I'm trying to extend battery life, and it looks like it's consuming about 40mA.
The onboard esp32 is probably most of that.

It would be a nice feature to add a sleep function to turn it off for a period of time.
With a sleep function I would expect it to draw less than 5mA.
This would GREATLY help in long term temperature monitoring applications.
As a bonus, a deep sleep option would allow for a reset on command.
This would allow for changing addresses without powering off the m5.
The start up time seems fast enough to not need a light sleep option.
It could be a 16 bit register accepting sleep times in mS.
Or an 8 bit register accepting sleep times in seconds.
I would prefer 16 bit.

Is it possible to wake on an I2C command?
An even better option would be an auto sleep, with a wake on I2C command.
Then the device spends most of its time asleep and only wakes when a temperature reading is needed.

**Comment by lovyan03** [comment]
@JasonPittenger 
Thank you for your feedback !
I have reviewed the source of the firmware and are on the verge of reducing power consumption by lowering the CPU clock, and will update the firmware soon.

Our expectation is that power consumption can be improved to less than 10mA. We also plan to implement a specified time sleep.

Unfortunately, it is difficult to implement the wake-up command. During sleep, the device loses its function as an I2C slave and cannot receive commands.
It is possible to wake up when I2C SCL goes LOW, but it is not possible to receive I2C data at the moment it wakes up in time.

**Comment by JasonPittenger** [comment]
I wondered if wake on I2C was going to be impossible.
A timed sleep would be very useful!  Thanks!

What about adding the sleep with a wake on I2C SCL LOW as an additional option?
The user could set the pin low and high again to trigger a wake up.
Or perhaps send a dummy byte to trigger the wake up.

**Comment by JasonPittenger** [comment]
Are there any updates on this issue?

**Comment by lovyan03** [comment]
I apologize for the very long wait.
I'm currently working on this project, but it is taking longer than initially anticipated because of unstable operation due to the reduced clock, which has caused the received data to be out of sequence, etc.
As soon as the problem is resolved, we will move on to the update work. Please wait for a while longer...

**Comment by JasonPittenger** [comment]
Thank you for the update and for the continued work!

**Comment by JasonPittenger** [comment]
Are there any updates on this?  I'm looking to reduce power consumption on my project.

**Comment by lovyan03** [comment]
@JasonPittenger 
I apologize for this.
There were discrepancies in the communication of information within the company, and the project progress was stalled due to confusion between hardware specification problems and firmware defects.
I am currently working towards a public release, so please be patient for a while longer.

**Comment by lovyan03** [comment]
@JasonPittenger 
Thank you for your patience. Firmware ver 1.1 is now officially available.
You can build the source code of this repository by yourself and write it to Unit, 
or you can use the firmware updater in M5BurnerV3.

![image](https://user-images.githubusercontent.com/42724151/219937037-c96f2797-46ad-4cd5-87d6-1406e4558e72.png)

**Comment by JasonPittenger** [comment]
I just updated my KMeter today.

Can you clarify usage?
Do I need to call setSleepTime(4) every time before I call sleep(false)?
Or do I need to call setSleepTime(4) one time at power up?
Or do I need to call  setSleepTime(4) one time to configure and it will be remembered forever?

**Comment by lovyan03** [comment]
Here is a link to the answer to the same question.

https://github.com/m5stack/M5Unit-KMeter/issues/1#issuecomment-1450976535
> The set values are stored in the unit's NVS and restored at wake-up.
> In other words, once it is executed, it does not need to be executed again when the power is turned back on.
